language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  include:
    - php: 5.5
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.4.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.5.*'
    - php: 5.5
      env: SYMFONY_VERSION='2.6.*'
    - php: 5.5
      env: SYMFONY_VERSION='dev-master'

before_script:
  - composer self-update
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/framework-bundle=$SYMFONY_VERSION; fi;'
  - composer install --prefer-source

script:
  - phpunit --coverage-text

install: composer install
